title: Miraj Rahman Sanjid
logo: assets/img/SEMO Headshots_Feb-25-6857-Photos by John Gerard Photography-modified.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
